config/routes.rb
Rails.application.routes.draw do

  root to: 'movies#index'

  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  namespace :admin do
    get '/users/debug' => 'users#debug'
    get '/users/exit_debug' => 'users#exit_debug'
    resources :users
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  # require 'pry'

  # def search
  #   # binding.pry
  #   # @movies = Movie.search()
  # end

  def index
    # binding.pry
    @movies = Movie.search(params)
    # binding.pry
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def edit
    # binding.pry
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])

   if @movie.update(post_params)
    redirect_to movies_path
   else
    render :edit
   end
  end

  def new
    @movie = Movie.new
  end

  def create  
    @movie = Movie.new(post_params)

    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  protected

  def post_params
    params.require(:movie).permit(:title, :director, :runtime_in_minutes, :description, :poster_image_url, :release_date, :poster_image)
  end

end

app/helpers/movies_helper.rb
module MoviesHelper

  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end
  
end

app/views/movies/_form.html.erb
<%= form_for @movie, html: { multipart: true } do |f| %>
  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
       <ul>
         <% @movie.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>

  <% end %>

  <div>
    <%= f.label "title" %><br>
    <%= f.text_field "title" %>
  </div>
  <div>
    <%= f.label "director" %><br>
    <%= f.text_field "director" %>
  </div>
  <div>
    <%= f.label "runtime_in_minutes" %><br>
    <%= f.text_field "runtime_in_minutes" %>
  </div>
  <div>
    <%= f.label "description" %><br>
    <%= f.text_area "description" %>
  </div>
  <div>
    <%= f.label :poster_image_url %><br>
    <%= f.file_field :poster_image_url %>
    <% if f.object.poster_image_url? %>
      <%= image_tag f.object.poster_image_url.thumb.url %>
      <%= f.label :remove_poster_image_url %>
      <%= f.check_box :remove_poster_image_url %> 
    <% end %>
  </div>
  <div>
    <%= f.label "release_date" %><br>
    <%= f.date_field "release_date" %>
  </div>
  <div>
    <%= f.submit "Save" %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<h4><%= link_to movie.title, movie_path(movie) %>(<%= link_to "edit", edit_movie_path(movie) %>, <%= link_to "delete", movie_path(movie), :method => :delete, :"data-confirm" => "You sure?" %>)</h4>
<p><%= movie.director %></p>
<p><%= movie.runtime_in_minutes %></p>
<p><%= movie.description %></p>
<p><%= movie.poster_image_url %></p>
<p><%= movie.release_date %></p>

app/views/movies/_search.html.erb
<%= form_tag(movies_path, method: "get") do %>
<!--   <div>
    <%= label_tag(:name, "Name:") %>
    <%= text_field_tag(:name) %>
  </div>
  <div>
    <%= label_tag(:director, "Director") %>
    <%= text_field_tag(:director) %>
  </div> -->
  <div>
    <%= text_field_tag :query, nil, placeholder: "Movie Title Or Director" %>
  </div>
  <div>
  <%= select_tag "duration", options_for_select(["Under 90 minutes","Between 90 and 120 minutes","Over 120 minutes"], params[:duration]) %>
  </div>

  <div>
    <%= submit_tag("Search") %>
  </div>
  
<% end %>

app/views/movies/edit.html.erb
<h1>Movies#edit</h1>
<p>Find me in app/views/movies/edit.html.erb</p>

<h2>Edit a Movie </h2>
<%= render 'form' %>

app/views/movies/index.html.erb
<h1>Movies#index</h1>
<p>Find me in app/views/movies/index.html.erb</p>

<p><%= link_to "Submit a New Movie", new_movie_path %></p>
<hr>
<h2>Search for a movie</h2>
<%= render 'search' %>
<%= render partial: "movie", collection: @movies %>

app/views/movies/new.html.erb
<h1>Movies#new</h1>
<p>Find me in app/views/movies/new.html.erb</p>

<h2>Create a New Movie </h2>

<%= render 'form' %>

app/views/movies/show.html.erb
 <%= link_to "Back to all movies", movies_path %><br/>

 <h2><%= @movie.title %> (<%= link_to "edit", edit_movie_path(@movie) %>, <%= link_to "delete", movie_path(@movie), method: :delete, confirm: "You sure?" %>)</h2>
 <%= image_tag @movie.poster_image_url.thumb.url %>
 <h3><%= formatted_date(@movie.release_date) %></h3>
 <h4>Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</h4>
 <p><%= @movie.description %></p>

 <hr>

 <h3>Reviews of <em><%= @movie.title %></em></h3>
  Average Movie Rating: <%= @movie.review_average %>/10

 <% if current_user %>
  <% @movie.reviews.each do |review| %>
    <p><%= review.text %></p>
    <p><%= review.rating_out_of_ten %>/10</p>
    <small>- <%= link_to review.user.full_name, user_path(review.user) %></small><br/>
  <% end %>
   <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
 <% else %>
   <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p> 
 <% end %>