config/routes.rb
Rails.application.routes.draw do

  root to: 'movies#index'

  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  namespace :admin do
    get '/users/debug' => 'users#debug'
    get '/users/exit_debug' => 'users#exit_debug'
    resources :users
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :reviews, dependent: :destroy

  has_secure_password

  validates :email,
    presence: true

  validates :firstname,
    presence: true

  validates :lastname,
    presence: true

  validates :password,
    length: { in: 6..20 }, on: :create

    def full_name
        "#{firstname} #{lastname}"
      end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_filter :check_if_admin

  def show
    @user = User.find(params[:id])
  end

  def new
    # binding.pry
    @user = User.new
  end

  def debug
    # binding.pry
    session[:super_user_id] = current_user.id
    session[:user_id] = params[:user_id]
    redirect_to movies_path
  end

  def exit_debug
    session[:user_id] = session[:super_user_id]
    session[:super_user_id] = nil
    redirect_to admin_users_path
  end

  def create
    @user = User.new(user_params)
    # binding.pry
    if @user.save
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_users_path
    else
      render :edit
    end

  end

  def index
    @users = User.all.page(params[:page]).per(2)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    UserMailer.delete_user_email(@user)
    redirect_to admin_users_path
  end

  def check_if_admin
    if !current_user || current_user.admin == 0
      flash[:alert] = "You are not an admin"
      redirect_to movies_path
    end
  end

  protected

 def user_params
   params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :admin)
 end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
 def new
   @user = User.new
 end

 def show
  @user = User.find(params[:id])
 end

 def create
   @user = User.new(user_params)

   if @user.save
    session[:user_id] = @user.id
    redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
   else
     render :new
   end
 end

 protected

 def user_params
   params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :admin)
 end

end

  

app/helpers/admin/user_helper.rb
module Admin::UserHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>Edit A New User</h1>
  <%= form_for @user, url: admin_user_path do |f| %>
    <% if @user.errors.any? %>
      <div>
        <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div>
      <%= f.label :firstname, "First Name" %><br>
      <%= f.text_field :firstname %>
    </div>
    <div>
      <%= f.label :lastname, "Last Name" %><br>
      <%= f.text_field :lastname %>
    </div>
    <div>
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>
    <div>
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
    </div>
     <div>
      <%= f.label "admin?" %><br>
      <%= f.check_box :admin %>
    </div>
    <div><%= f.submit "Submit" %></div>
<% end %>

app/views/admin/users/index.html.erb
  <h2>Users </h2>

  <%= paginate @users %>

  <p> <%= link_to "Create a new User", new_admin_user_path %></p>

  <% @users.each do |user| %>
  <%= link_to "edit", edit_admin_user_path(user) %>
    <p><%= link_to "View As User", admin_users_debug_path(user_id: user.id) %></p>
    <p>User First Name: <%= user.firstname %></p>
    <p>User Last Name: <%= user.lastname %></p>
    <p>User email: <%= link_to user.email, admin_user_path(user) %></p>
    <p>Password: <%= user.password_digest %></p>
    <p><%= link_to "delete", admin_user_path(user), :method => :delete, :"data-confirm" => "You sure?" %><p>
    <hr>
  <% end %>

app/views/admin/users/new.html.erb
<h1>Create A New User</h1>
  <%= form_for @user, url: admin_users_path do |f| %>
    <% if @user.errors.any? %>
      <div>
        <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div>
      <%= f.label :firstname, "First Name" %><br>
      <%= f.text_field :firstname %>
    </div>
    <div>
      <%= f.label :lastname, "Last Name" %><br>
      <%= f.text_field :lastname %>
    </div>
    <div>
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>
    <div>
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
    </div>
     <div>
      <%= f.label "admin?" %><br>
      <%= f.check_box :admin %>
    </div>
    <div><%= f.submit "Submit" %></div>
<% end %>

app/views/admin/users/show.html.erb
<%= @user.inspect %>